# Generated by Django 3.2.6 on 2023-07-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quadro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(blank=True, default='', max_length=50)),
                ('Autor', models.CharField(blank=True, default='', max_length=50)),
                ('data_quadro', models.DateField(blank=True, default='')),
                ('Quadro', models.FileField(blank=True, default='', upload_to='')),
                ('avaliacao', models.FloatField(default=0.0)),
            ],
        ),
    ]
