# Generated by Django 3.2.6 on 2023-07-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20230729_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quadro',
            name='Quadro',
            field=models.CharField(blank=True, default='', max_length=1000000),
        ),
    ]
